name: Java CI with Gradle
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许创建 Release 和上传资产
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Get release version from tag
        id: tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Find built JAR file
        id: find-jar
        run: |
          JAR_PATH=$(find ./build/libs -name '*.jar' -not -name '*-plain.jar' -not -name '*-sources.jar' -not -name '*-javadoc.jar' | head -n 1)
          echo "JAR_PATH=$JAR_PATH" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ env.RELEASE_VERSION }}
          body: "Automated release for version ${{ env.RELEASE_VERSION }}"
          draft: false
          prerelease: false

      - name: Upload JAR Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.find-jar.outputs.JAR_PATH }}
          asset_name: app-${{ env.RELEASE_VERSION }}.jar
          asset_content_type: application/java-archive
